# Generated by Django 2.2.4 on 2019-08-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='organizatio',
            new_name='organization',
        ),
    ]
